# Use the official Node.js image as the base image
FROM node:22

# Set the working directory inside the container
WORKDIR /workspace/dungeon-crawler

# Install chokidar-cli globally (you can skip this if unnecessary)
RUN npm install -g chokidar-cli

# Copy the current project files into the container
COPY . .

# Install project dependencies
RUN npm install